---
- name: install epel-release
  yum:
    name: epel-release
    state: latest
- name: pip installation
  yum:
    name: python-pip
    state: latest
- name: Docker-compose installation
  pip:
    name: docker-compose

