---
- name: Running Consul container
  command: docker run -d -p 8500:8500 --name=consul progrium/consul -server -bootstrap
- name: Running Swarm Manager
  command: docker run -d -p 4000:4000 swarm manage -H :4000 --replication --advertise {{ controlhost }}:4000 consul://{{ controlhost }}:8500
